//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingWCFaplication.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SayHello", ReplyAction="http://tempuri.org/IService1/SayHelloResponse")]
        string SayHello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SayHello", ReplyAction="http://tempuri.org/IService1/SayHelloResponse")]
        System.Threading.Tasks.Task<string> SayHelloAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisplayAllCars", ReplyAction="http://tempuri.org/IService1/DisplayAllCarsResponse")]
        string DisplayAllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisplayAllCars", ReplyAction="http://tempuri.org/IService1/DisplayAllCarsResponse")]
        System.Threading.Tasks.Task<string> DisplayAllCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintMenu", ReplyAction="http://tempuri.org/IService1/PrintMenuResponse")]
        string PrintMenu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintMenu", ReplyAction="http://tempuri.org/IService1/PrintMenuResponse")]
        System.Threading.Tasks.Task<string> PrintMenuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisplayAllCarsCompany", ReplyAction="http://tempuri.org/IService1/DisplayAllCarsCompanyResponse")]
        string DisplayAllCarsCompany();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisplayAllCarsCompany", ReplyAction="http://tempuri.org/IService1/DisplayAllCarsCompanyResponse")]
        System.Threading.Tasks.Task<string> DisplayAllCarsCompanyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompanyContacts", ReplyAction="http://tempuri.org/IService1/GetCompanyContactsResponse")]
        string GetCompanyContacts(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompanyContacts", ReplyAction="http://tempuri.org/IService1/GetCompanyContactsResponse")]
        System.Threading.Tasks.Task<string> GetCompanyContactsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisplayAllCompanyCarsByName", ReplyAction="http://tempuri.org/IService1/DisplayAllCompanyCarsByNameResponse")]
        string DisplayAllCompanyCarsByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisplayAllCompanyCarsByName", ReplyAction="http://tempuri.org/IService1/DisplayAllCompanyCarsByNameResponse")]
        System.Threading.Tasks.Task<string> DisplayAllCompanyCarsByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UsingWCFaplication.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UsingWCFaplication.ServiceReference1.IService1>, UsingWCFaplication.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(string name) {
            return base.Channel.SayHello(name);
        }
        
        public System.Threading.Tasks.Task<string> SayHelloAsync(string name) {
            return base.Channel.SayHelloAsync(name);
        }
        
        public string DisplayAllCars() {
            return base.Channel.DisplayAllCars();
        }
        
        public System.Threading.Tasks.Task<string> DisplayAllCarsAsync() {
            return base.Channel.DisplayAllCarsAsync();
        }
        
        public string PrintMenu() {
            return base.Channel.PrintMenu();
        }
        
        public System.Threading.Tasks.Task<string> PrintMenuAsync() {
            return base.Channel.PrintMenuAsync();
        }
        
        public string DisplayAllCarsCompany() {
            return base.Channel.DisplayAllCarsCompany();
        }
        
        public System.Threading.Tasks.Task<string> DisplayAllCarsCompanyAsync() {
            return base.Channel.DisplayAllCarsCompanyAsync();
        }
        
        public string GetCompanyContacts(string name) {
            return base.Channel.GetCompanyContacts(name);
        }
        
        public System.Threading.Tasks.Task<string> GetCompanyContactsAsync(string name) {
            return base.Channel.GetCompanyContactsAsync(name);
        }
        
        public string DisplayAllCompanyCarsByName(string name) {
            return base.Channel.DisplayAllCompanyCarsByName(name);
        }
        
        public System.Threading.Tasks.Task<string> DisplayAllCompanyCarsByNameAsync(string name) {
            return base.Channel.DisplayAllCompanyCarsByNameAsync(name);
        }
    }
}
